       PROGRAM ASTAP
C
       PARAMETER(MXNODE= 20000, MXCOND= 100000, MXUARY=  5000)
       PARAMETER(MXTARY=  10000,MXMODS= 100,  MXTOKN=  80)
       PARAMETER(MXCNTR=  76,MXUCON= 1000,  MXNCON= 5000)
       PARAMETER(MXFRES= 196,MXFILE=  17)
       PARAMETER(MXFLID=  30,MXMODF= 100)
        COMMON /FLUDAT/ FI(90),FDATA(1700)
        COMMON /FLUARY/ NFPARY,FPARAY(        1)
        INTEGER FI
       PARAMETER (MXFMOD=        1)
       PARAMETER (MXLUMP=        3)
       PARAMETER (MXTANK=        2)
       PARAMETER (MXJUNC=        1)
       PARAMETER (MXPLEN=        1)
       PARAMETER (MXPATH=        2)
       PARAMETER (MXTUBE=        1)
       PARAMETER (MXCONN=        2)
       PARAMETER (KCMAX=       36)
       PARAMETER (NDMAX=        6)
       PARAMETER (NOMAX=        6)
       PARAMETER (NIA=       14)
       PARAMETER (NJA=       72)
       PARAMETER (NARO=       12)
       PARAMETER (NWORKT=      440)
       PARAMETER (MXTIE =        1)
       PARAMETER (MXMACS=        1)
       PARAMETER (MXGNLU=        1)
       PARAMETER (MXGNCN=        1)
       PARAMETER (MXGNTI=        1)
        COMMON/LUMP1 / LTYPE(MXLUMP)
        COMMON/LUMP2 / LINKL(MXPATH*2)
        COMMON/LUMP2A/ LNKPT(MXPATH*2)
        COMMON/LUMP3 / NLINKL(MXLUMP)
        COMMON/LUMP4 / HL(MXLUMP)
        COMMON/LUMP5 / PL(MXLUMP)
        COMMON/LUMP6 / XL(MXLUMP)
        COMMON/LUMP6A/ XSHIFT(MXLUMP)
        COMMON/LUMP7 / TL(MXLUMP)
        COMMON/LUMP7A/ DL(MXLUMP)
        COMMON/LUMP8 / UTANK(MXTANK)
        COMMON/LUMP9 / EMTANK(MXTANK)
        COMMON/LUMP10/ VOL(MXTANK)
        COMMON/LUMP11/ VDOT(MXTANK)
        COMMON/LUMP12/ QDOT(MXLUMP)
        COMMON/LUMP13/ DUDT(MXTANK)
        COMMON/LUMP14/ DMDT(MXTANK)
        COMMON/LUMP15/ DHDUM(MXTANK)
        COMMON/LUMP16/ DHDMU(MXTANK)
        COMMON/LUMP17/ DPDUM(MXTANK)
        COMMON/LUMP18/ DPDMU(MXTANK)
        COMMON/LUMP19/ VDASHP(MXTANK)
        COMMON/LUMP20/ VDASHH(MXTANK)
        COMMON/LUMP21/ LMPINT(MXLUMP)
        COMMON/LUMP22/ PLOLD(MXLUMP) 
        COMMON/LUMP23/ TLOLD(MXLUMP)
        COMMON/LUMP24/ DLOLD(MXLUMP)
        COMMON/LUMP26/ DPUP(MXLUMP)
        COMMON/LUMP27/ DPDOWN(MXLUMP)
        COMMON/LUMP29/ LMPSTA(MXLUMP)
        COMMON/LUMP30/ COMP(MXTANK)
        COMMON/LUMP31/ CX(MXLUMP)
        COMMON/LUMP32/ CY(MXLUMP)
        COMMON/LUMP33/ CZ(MXLUMP)
        COMMON/LUMP34/ VDOTC(MXTANK)
        COMMON/LUMP35/ DLL(MXLUMP)
        COMMON/LUMP36/ DLV(MXLUMP)
        COMMON/LUMP37/ HFGL(MXLUMP)
        DOUBLE PRECISION PL,PLOLD
        DIMENSION DHDUP(1),DHDPU(1),DRDU(1),LHARD(1),DPEST(1)
     .             ,DTFACT(1)
        EQUIVALENCE (LHARD,DPDMU),(DHDUP,DHDUM),(DHDPU,DHDMU)
     +          ,(DRDU,DPDUM),(VDASHP,DPEST),(VDASHH,DTFACT)
        COMMON/PATH1 / KTYPE(MXPATH)
        COMMON/PATH2 / IJK(2,MXPATH)
        COMMON/PATH3 / FR(MXPATH)
        COMMON/PATH4 / HC(MXPATH)
        COMMON/PATH5 / FC(MXPATH)
        COMMON/PATH6 / AC(MXPATH)
        COMMON/PATH7 / GK(MXPATH)
        COMMON/PATH8 / CSUBK(MXPATH)
        COMMON/PATH9 / LVS(MXPATH)
        COMMON/PATH10/ HK(MXPATH)
        COMMON/PATH11/ ENTUPK(MXPATH)
        COMMON/PATH12/ DWDT(MXTUBE)
        COMMON/PATH13/ DH(MXPATH)
        COMMON/PATH14/ TLEN(MXPATH)
        COMMON/PATH15/ AF(MXPATH)
        COMMON/PATH16/ WRF(MXPATH)
        COMMON/PATH17/ UPF(MXPATH)
        COMMON/PATH18/ IPDC(MXPATH)
        COMMON/PATH19/ NDEVIC(MXPATH)
        COMMON/PATH20/ PATINT(MXPATH)
        COMMON/PATH21/ FROLD(MXPATH)
        COMMON/PATH22/ DPOLD(MXPATH)
        COMMON/PATH23/ DUPI(MXPATH)
        COMMON/PATH24/ DUPJ(MXPATH)
        COMMON/PATH25/ HCBF(MXTUBE)
        COMMON/PATH26/ FPOW(MXPATH)
        COMMON/PATH27/ IDT(MXPATH)
        COMMON/PATH28/ IREG(MXPATH)
        COMMON/PATH29/ JREG(MXPATH)
        COMMON/PATH30/ EI(MXPATH)
        COMMON/PATH31/ EJ(MXPATH)
        COMMON/PATH32/ DK(MXPATH)
        COMMON/PATH33/ FD(MXPATH)
        COMMON/PATH34/ FG(MXPATH)
        COMMON/PATH35/ AM(MXTUBE)
        COMMON/PATH36/ HIOLD(MXPATH)
        COMMON/PATH37/ HJOLD(MXPATH)
        COMMON/PATH38/ HKOLD(MXPATH)
        COMMON/PATH39/ DACFR(MXPATH)
        COMMON/PATH40/ AFTH(MXPATH)
        COMMON/PATH41/ FK(MXPATH)
        INTEGER PATINT
        COMMON/SOLN1 / ACOEFF(KCMAX)
        COMMON/SOLN2 / BCONST(NOMAX)
        COMMON/SOLN3 / DELSOL(NDMAX)
        COMMON/SOLN4 / IACOEF(NIA)
        COMMON/SOLN5 / JACOEF(NJA)
        COMMON/SOLN6 / AROWS1(NOMAX)
        COMMON/SOLN6A/ AROWS2(NOMAX)
        COMMON/SOLN7 / IOR(NOMAX)
        COMMON/SOLN8 / DWORK(NWORKT)
        COMMON/SOLN9 / MWORK(2,MXFMOD)
        COMMON/SOLN12/ SOLT(MXFMOD)
        COMMON/SOLN15/ FLIP(MXFMOD)
        COMMON/SOLN17/ NUMHT(MXFMOD)
        COMMON/SOLN18/ NORDER(MXFMOD)
        COMMON/SOLN19/ NORD0(MXFMOD)
        COMMON/SOLN20/ LIMTNK(MXFMOD)
        COMMON/SOLN21/ LIMTUB(MXFMOD)
        COMMON/SOLN22/ KC(MXFMOD)
        COMMON/SOLN23/ NACOEF,NICOEF,NJCOEF,DELTAT(MXFMOD)
        COMMON/SOLN24/ NWORK(MXFMOD)
        COMMON/SOLN25/ DTIMEF(MXFMOD)
        COMMON/SOLN26/ LIMMES(MXFMOD)
        COMMON/SOLN27/ SSCMES(MXFMOD)
        COMMON/SOLN28/ LSTMES(MXFMOD)
        CHARACTER*32 LIMMES
        CHARACTER*60 LSTMES
        CHARACTER*100 SSCMES
        DOUBLE PRECISION ACOEFF,DELSOL,AROWS1,AROWS2,DWORK,BCONST
        DIMENSION IWORK(1)
        EQUIVALENCE (DWORK,IWORK)
        LOGICAL FLIP
        COMMON/FSIZ1 / NFM,NTL,NTT,NTJ,NTPL,NTK,NTTB,NTC
        COMMON/FSIZ2 / NUMTNK(MXFMOD)
        COMMON/FSIZ3 / NUMJNC(MXFMOD)
        COMMON/FSIZ4 / NUMPLE(MXFMOD)
        COMMON/FSIZ5 / NUMTUB(MXFMOD)
        COMMON/FSIZ6 / NUMCNT(MXFMOD)
        COMMON/FSIZ7 / NTOTL(MXFMOD)
        COMMON/FSIZ8 / NTOTK(MXFMOD)
        COMMON/FSIZ9 / MAXPTH(MXFMOD)
        COMMON/FSIZ11/ FLID(MXFMOD)
        INTEGER FLID
       PARAMETER (MXCLIS=        7)
       PARAMETER (MXRESN=        8)
        COMMON /HSHDT/ NTIM0
        COMMON /HSHDT1/ NTIMUP(MXRESN)
        COMMON /HSHDT2/ NTIMDN(MXRESN)
        COMMON /HSHDT3/ KEYS(2,MXRESN)
        COMMON /HSHDT4/ HSHDAT(MXCLIS,       31)
        COMMON /HSHDT5/ PLNAMS(MXRESN)
        COMMON /HSHDT6/ DELTMX,MXRSON,MXPRIM,NXTHSH,DATA(5,MXRESN)
        COMMON /HSHDT7/ ROWSTK(MXRESN)
        COMMON /HSHDT8/ ONSTK
        INTEGER HSHDAT,ROWSTK,ONSTK
       CHARACTER*4 PLNAMS
       COMMON/FLUCNT/DTSIZF(MXMODF),DTMAXF(MXMODF),OUTPTF(MXMODF),
     . RSSIZF(MXMODF) ,RSMAXF(MXMODF) ,RERRF(MXMODF),
     . REBALF(MXMODF) ,ITROTF(MXMODF) ,OPITRF(MXMODF),
     . DTMINF(MXMODF) ,ITHLDF(MXMODF),
     . DTTUBF(MXMODF) ,RSTUBF(MXMODF)
        COMMON /FLUCN1/ PATMOS,UID,ACCELX,ACCELY,ACCELZ
        DOUBLE PRECISION PATMOS
        INTEGER UID,OPITRF
        COMMON /TIEDAT/ NTIET
        COMMON /TIEDA1/ PNTTIE(MXFMOD)
        COMMON /TIEDA2/ NUMTIE(MXFMOD)
        COMMON /TIEDA3/ LMPTIE(MXTIE)
        COMMON /TIEDA4/ TIETYP(MXTIE)
        COMMON /TIEDA5/ PATTIE(2,MXTIE)
        COMMON /TIEDA6/ AFRACT(2,MXTIE)
        COMMON /TIEDA7/ UA(MXTIE)
        COMMON /TIEDA8/ NODTIE(MXTIE)
        COMMON /TIEDA9/ PNGTIE(MXTIE)
        COMMON /TIEDAA/ TIEINT(MXTIE)
        COMMON /TIEDAB/ LNKTIL(MXLUMP+MXTIE)
        COMMON /TIEDAC/ LNKPTL(MXLUMP+MXTIE)
        COMMON /TIEDAD/ LNKTIN(        1+MXTIE)
        COMMON /TIEDAE/ LNKPTN(        1+MXTIE)
        COMMON /TIEDAF/ QTIE(MXTIE)
        COMMON /TIEDAG/ QTOLD(MXTIE)
        COMMON /TIEDAH/ QTOL2(MXTIE)
        COMMON /TIEDAI/ UAOLD(MXTIE)
        COMMON /TIEDAJ/ UAOL2(MXTIE)
        COMMON /TIEDAK/ NDTYPE(MXTIE)
        COMMON /TIEDAL/ GDNODE(MXTIE)
        COMMON /TIEDAM/ GDLUMP(MXTIE)
        COMMON /TIEDAN/ DUPL(MXTIE)
        COMMON /TIEDAO/ DUPN(MXTIE)
        COMMON /TIEDAP/ ROTTIN(        1)
        COMMON /TIEDAQ/ ROTTIL(MXLUMP)
        COMMON /TIEDAR/ UAFACT(MXTIE)
        LOGICAL GDNODE,GDLUMP
        INTEGER PNTTIE,PATTIE,TIETYP,PNGTIE,TIEINT,ROTTIN,ROTTIL
        COMMON / MACRO1 / MIDNOS(MXMACS)
        COMMON / MACRO2 / MININT(MXMACS)
        COMMON / MACRO3 / PNT1L(MXMACS)
        COMMON / MACRO4 / PNT1P(MXMACS)
        COMMON / MACRO5 / PNT1T(MXMACS)
        COMMON / MACRO6 / MLMPCT(MXMACS)
        COMMON / MACRO7 / MPTHCT(MXMACS)
        COMMON / MACRO8 / MTIECT(MXMACS)
        COMMON / MACRO9 / MLUMPS(MXGNLU)
        COMMON / MACROA / MPATHS(MXGNCN)
        COMMON / MACROB / MTIES(MXGNTI)
        COMMON / MACROC / TOTMAC,LASTMP,LASTML,LASTMT
        COMMON / MACROD / MACMOD(MXMACS)
        INTEGER PNT1L,PNT1P,PNT1T,TOTMAC,LASTML,LASTMP,LASTMT
        COMMON/JUNC1 / SKIP(MXJUNC)
        COMMON/JUNC2 / JEXTRA(MXJUNC)
        COMMON/JUNC3 / EPSK(       25,MXJUNC)
        COMMON/JUNC4 / LMP(       25,MXJUNC)
        COMMON/JUNC5 / NTIEJ(MXJUNC)
        LOGICAL SKIP
       COMMON /BLANK1/  NDIM1    , NTH1  , EXTRA1(MXNODE)
       COMMON /BLANK2/  NDIM2    , NTH2  , EXTRA2(MXNODE)
       COMMON /BLANK3/  NDIM3    , NTH3  , EXTRA3(MXNODE)
       COMMON /BLANK4/  NDIM4    , NTH4  , EXTRA4(MXNODE)
       COMMON /BLANK5/  NDIM5    , NTH5  , EXTRA5(MXNODE)
       COMMON /BLANK6/  NDIM6    , NTH6  , EXTRA6(MXNODE)
C
       COMMON /BLDAT  /   NSEQ(MXMODS)
       COMMON /BLDAT1 /   FIG
       CHARACTER*8        FIG
C
       COMMON /CCONST /   MMODS   , NNOD    , ABSZRO  , SIGMA
     +                  , NMACT   , DATE    , TIMDY   , LINECT
     +                  , PAGECT  , DTIMES  , TIMEN   , TIMEO
     +                  , TIMEM   , TIMEND  , NLOOPS  , LOOPCT
     +                  , MLINE
       INTEGER            LINECT  , PAGECT
C
       COMMON /DIMENS /   NND     , NNA     , NNH     , NNT
     +                  , NGT     , NCON    , NARYP   , NSEQU
     +                  , NSEQB   , NVC     , NVG
C
       COMMON /HEAD   /   NVRSN   , LMDTE   , NDTE    , NTME
     +                  , NJOB    , MDLNNM  , NTITLE  , ITITLE
       CHARACTER*6        NVRSN   , LMDTE   , NDTE    , NTME
       CHARACTER*8        NJOB    , MDLNNM
       CHARACTER*66       NTITLE  , ITITLE
C
       COMMON /TAPES  /   NIN     , NOUT    , NCOND   , NNODE
     +                  , NOSORC  , NOARRY  , NOCARY  , NOTARY
     +                  , NVCD    , NVGD    , NOUSER  , NOCNTR
     +                  , NOUSE   , NETQF   , NXTRA1  , NXTRA2
     +                  , NTSV    , NUSER1  , NUSER2  , NRSI  
     +                  , NRSO    , NPARAM  , NFLOW   , NFLOW2
     +                  , NFLOW3  , NOOPT   , NSCR1   , NSCR2 
     +                  , NSCR3   , NSCR4   , NQMP    , NFPROP
C
       COMMON /BEGEND /   IBEGC(MXMODS) , IENDC(MXMODS)
     +                  , IBEGG(MXMODS) , IENDG(MXMODS)
C
       COMMON /USER/  USRDAT(      28)
       COMMON /CNTRL1 /
     +       DTIMEU(MXMODS) , DTIMEI(MXMODS) , DTIMEL(MXMODS)
     +     , DTIMEH(MXMODS) , OUTPUT(MXMODS) , DTMPCC(MXMODS)
     +     , DTMPCA(MXMODS) , NDTMPN(MXMODS) , ITHOLD(MXMODS)
     +     , ATMPCA(MXMODS) , NATMPN(MXMODS) , DRLXCA(MXMODS)
     +     , NDRLXN(MXMODS) , ARLXCA(MXMODS) , ARLXCC(MXMODS)
     +     , NARLXN(MXMODS) , CSGMIN(MXMODS) , CSGFAC(MXMODS)
     +     , CSGMAX(MXMODS) , NCSGMN(MXMODS) , NCGMAN(MXMODS)
     +     , EBALSA(MXMODS) , EBALNA(MXMODS) , EBALSC(MXMODS)
     +     , EBALNC(MXMODS) , NEBALN(MXMODS) , NLOOPT(MXMODS)
     +     , EXTLIM(MXMODS) , ITERXT(MXMODS) , ITEROT(MXMODS)
     +     , BACKUP(MXMODS) , OPEITR(MXMODS) , DRLXCC(MXMODS)
     +     , ATMPCC(MXMODS) , ESUMIS(MXMODS) , ESUMOS(MXMODS)
       INTEGER            OPEITR
C
       COMMON /CNTRL2 /   NDTMPC(MXMODS) , NATMPC(MXMODS)
     +     , NDRLXC(MXMODS) , NARLXC(MXMODS) , NCSGMC(MXMODS)
     +     , NCGMAC(MXMODS) , NEBALC(MXMODS)
       CHARACTER*8        NDTMPC      , NATMPC
     +                  , NDRLXC      , NARLXC      , NCSGMC
     +                  , NCGMAC      , NEBALC
C
       COMMON /MODNM1 /   MNAMES(MXMODS)
       COMMON /MODNM2 /   MLLINK(MXMODS)
       COMMON /MODNM3 /   MRLINK(MXMODS)
       COMMON /MODNM4 /   MACT(MXMODS)
       COMMON /MODNM5 /   MROOT
       CHARACTER*8        MNAMES
C
       COMMON /TITL   /   TITLE
       CHARACTER*120      TITLE
C
       COMMON /NUMCON /   K(       1)
       COMMON /ARAYS  /   A(       1)
       COMMON /CARAYS /   UCA(       1)
       DIMENSION          XK(1)   , NA(1)
       CHARACTER*128 UCA
       EQUIVALENCE (XK(1), K(1))
       EQUIVALENCE (NA(1), A(1))
C
       COMMON /CDAT1  /   PT(       1)
       COMMON /CDAT2  /   PG(       1)
       COMMON /CDAT3  /   NLIN(       1)
       COMMON /CDAT4  /   NRAD(       1)
       COMMON /CDAT7  /   NCTOT(       1)
       COMMON /CDAT8  /   NGSTRT(       1)
       COMMON /CDAT9  /   G(       1)
       INTEGER            PT      , PG      , NLIN    , NRAD
       INTEGER            NCTOT   , NGSTRT
C
       COMMON /VARC   /   VC(       1)
C
       COMMON /VARG   /   VG(       1)
C
       COMMON /NDAT1  /   T(       1)
       COMMON /NDAT2  /   C(       1)
       COMMON /NDAT3  /   Q(       1)
       COMMON /NDAT4  /   NMOD(       1)
       COMMON /NDAT5  /   NSTRT(       1)
       COMMON /NDAT6  /   NMDIF(       1)
       COMMON /NDAT7  /   NMARI(       1)
       COMMON /NDAT8  /   NMHT(       1)
       COMMON /NDAT9  /   NMBD(       1)
       COMMON /NDAT10 /   NDNAM(       1)
       COMMON /NDAT11 /   NDINT(       1)
       COMMON /NDAT12 /   TOLD(       1)
       COMMON /NDAT13 /   QOLD(       1)
       CHARACTER*8        NMOD    ,NDNAM
C
       COMMON /DATQVT/ QVTDAT(8,       1)
       COMMON /MODQVT/ MODLQS(2,       1)
       COMMON /TARY1 / TARY(     1)
       COMMON /TARY2 / NUMREC(     1)
       COMMON /TARY3 / NPNT(2,     1)
       COMMON /TARY4 / NTREC(     1)
       COMMON /TARY5 / TIME1(     1)
       COMMON /TARY6 / TIMEH(     1)
       COMMON /TARY7 / TARYL(     1)
       COMMON /TARY8 / TIME1L(     1)
       COMMON /TARY9/ TIMEHL(     1)
        COMMON /SAVCPA/ HAVCPA
        COMMON /SAVCP1/ CPAFID(2,    1)
        COMMON /SAVCP2/ CPIARY(    1)
        INTEGER HAVCPA,CPAFID
        REAL CPIARY
       COMMON /FLONM1 /   FLONAM(MXFMOD)
       COMMON /FLONM2 /   FLLINK(MXFMOD)
       COMMON /FLONM3 /   FRLINK(MXFMOD)
       COMMON /FLONM4 /   RACT(MXFMOD)
       COMMON /FLONM5 /   THRPNT(MXFMOD)
       COMMON /FLONM6 /   FROOT,NUMFLM
       CHARACTER*8 FLONAM
       INTEGER FLLINK,FRLINK,RACT,THRPNT,FROOT,NUMFLM
       EXTERNAL BLKDAT
 
       include '../prepro/data.fi'
 
 
       projectpath1 = 'balloon'
 
       call params_default
       call filenames_default
 
       CALL INITAL
       CALL READIN
       CALL OPER
C
       call filenames_cleanup_prep
C
       call filenames_cleanup
C
       STOP
       END
       SUBROUTINE FL1001
       PARAMETER(MXNODE= 20000, MXCOND= 100000, MXUARY=  5000)
       PARAMETER(MXTARY=  10000,MXMODS=100,  MXTOKN=80)
       PARAMETER(MXCNTR=76,MXUCON= 1000,  MXNCON= 5000)
       PARAMETER(MXFRES=196,MXFILE=17,  MXFLID= 30)
       PARAMETER(MXMODF=100)
        COMMON /FLUDAT/ FI(90),FDATA(1700)
        INTEGER FI
        DOUBLE PRECISION VPS,VPGMAX
       PARAMETER (MXFMOD=        1)
       PARAMETER (MXLUMP=        3)
       PARAMETER (MXTANK=        2)
       PARAMETER (MXJUNC=        1)
       PARAMETER (MXPLEN=        1)
       PARAMETER (MXPATH=        2)
       PARAMETER (MXTUBE=        1)
       PARAMETER (MXCONN=        2)
       PARAMETER (KCMAX=       36)
       PARAMETER (NDMAX=        6)
       PARAMETER (NOMAX=        6)
       PARAMETER (NIA=       14)
       PARAMETER (NJA=       72)
       PARAMETER (NARO=       12)
       PARAMETER (NWORKT=      440)
       PARAMETER (MXTIE =        1)
       PARAMETER (MXMACS=        1)
       PARAMETER (MXGNLU=        1)
       PARAMETER (MXGNCN=        1)
       PARAMETER (MXGNTI=        1)
        COMMON/LUMP4 / HL(MXLUMP)
        COMMON/LUMP5 / PL(MXLUMP)
        COMMON/LUMP6 / XL(MXLUMP)
        COMMON/LUMP7 / TL(MXLUMP)
        COMMON/LUMP7A/ DL(MXLUMP)
        COMMON/LUMP10/ VOL(MXTANK)
        COMMON/LUMP11/ VDOT(MXTANK)
        COMMON/LUMP12/ QDOT(MXLUMP)
        DOUBLE PRECISION PL
        COMMON/LUMP30/ COMP(MXTANK)
        COMMON/LUMP31/ CX(MXLUMP)
        COMMON/LUMP32/ CY(MXLUMP)
        COMMON/LUMP33/ CZ(MXLUMP)
        COMMON /TIEDAF/ QTIE(MXTIE)
        COMMON /TIEDAN/ DUPL(MXTIE)
        COMMON /TIEDAO/ DUPN(MXTIE)
        COMMON /TIEDA7/ UA(MXTIE)
        COMMON/PATH3 / FR(MXPATH)
        COMMON/PATH4 / HC(MXPATH)
        COMMON/PATH5 / FC(MXPATH)
        COMMON/PATH6 / AC(MXPATH)
        COMMON/PATH7 / GK(MXPATH)
        COMMON/PATH10/ HK(MXPATH)
        COMMON/PATH13/ DH(MXPATH)
        COMMON/PATH14/ TLEN(MXPATH)
        COMMON/PATH15/ AF(MXPATH)
        COMMON/PATH16/ WRF(MXPATH)
        COMMON/PATH17/ UPF(MXPATH)
        COMMON/PATH18/ IPDC(MXPATH)
        COMMON/PATH23/ DUPI(MXPATH)
        COMMON/PATH24/ DUPJ(MXPATH)
        COMMON/PATH26/ FPOW(MXPATH)
        COMMON/PATH30/ EI(MXPATH)
        COMMON/PATH31/ EJ(MXPATH)
        COMMON/PATH32/ DK(MXPATH)
        COMMON/PATH33/ FD(MXPATH)
        COMMON/PATH34/ FG(MXPATH)
        COMMON/PATH35/ AM(MXTUBE)
        COMMON/PATH40/ AFTH(MXPATH)
        COMMON/PATH41/ FK(MXPATH)
        COMMON/SOLN23/ NZZZZ1,NZZZZ2,NZZZZ3,DTIMUF(MXFMOD)
        COMMON/FSIZ1 / NFM,NTL,NTT,NTJ,NTPL,NTK,NTTB,NTC
        COMMON/FSIZ2 / NUMTNK(MXFMOD)
        COMMON/FSIZ3 / NUMJNC(MXFMOD)
        COMMON/FSIZ4 / NUMPLE(MXFMOD)
        COMMON/FSIZ5 / NUMTUB(MXFMOD)
        COMMON/FSIZ6 / NUMCNT(MXFMOD)
        COMMON/FSIZ7 / NTOTL(MXFMOD)
        COMMON/FSIZ8 / NTOTK(MXFMOD)
        COMMON/FSIZ11/ FLID(MXFMOD)
        INTEGER FLID
        COMMON/FLUCNT/DTSIZF(MXMODF),DTMAXF(MXMODF),OUTPTF(MXMODF),
     . RSSIZF(MXMODF) ,RSMAXF(MXMODF) ,RERRF(MXMODF),
     . REBALF(MXMODF) ,ITROTF(MXMODF) ,OPITRF(MXMODF),
     . DTMINF(MXMODF) ,ITHLDF(MXMODF),
     . DTTUBF(MXMODF) ,RSTUBF(MXMODF)
        COMMON /FLUCN1/ PATMOS,UID,ACCELX,ACCELY,ACCELZ
        DOUBLE PRECISION PATMOS
        INTEGER UID
       COMMON /CNTRL1 /
     +       DTIMEU(MXMODS) , DTIMEI(MXMODS) , DTIMEL(MXMODS)
     +     , DTIMEH(MXMODS) , OUTPUT(MXMODS) , DTMPCC(MXMODS)
     +     , DTMPCA(MXMODS) , NDTMPN(MXMODS) , ITHOLD(MXMODS)
     +     , ATMPCA(MXMODS) , NATMPN(MXMODS) , DRLXCA(MXMODS)
     +     , NDRLXN(MXMODS) , ARLXCA(MXMODS) , ARLXCC(MXMODS)
     +     , NARLXN(MXMODS) , CSGMIN(MXMODS) , CSGFAC(MXMODS)
     +     , CSGMAX(MXMODS) , NCSGMN(MXMODS) , NCGMAN(MXMODS)
     +     , EBALSA(MXMODS) , EBALNA(MXMODS) , EBALSC(MXMODS)
     +     , EBALNC(MXMODS) , NEBALN(MXMODS) , NLOOPT(MXMODS)
     +     , EXTLIM(MXMODS) , ITERXT(MXMODS) , ITEROT(MXMODS)
     +     , BACKUP(MXMODS) , OPEITR(MXMODS) , DRLXCC(MXMODS)
     +     , ATMPCC(MXMODS) , ESUMIS(MXMODS) , ESUMOS(MXMODS)
       INTEGER            OPEITR
C
       COMMON /CNTRL2 /   NDTMPC(MXMODS) , NATMPC(MXMODS)
     +     , NDRLXC(MXMODS) , NARLXC(MXMODS) , NCSGMC(MXMODS)
     +     , NCGMAC(MXMODS) , NEBALC(MXMODS)
       CHARACTER*8        NDTMPC      , NATMPC
     +                  , NDRLXC      , NARLXC      , NCSGMC
     +                  , NCGMAC      , NEBALC
C
       COMMON /NDAT1  /   T(       1)
       COMMON /NDAT2  /   C(       1)
       COMMON /NDAT3  /   Q(       1)
       COMMON /NDAT4  /   NMOD(       1)
       COMMON /NDAT5  /   NSTRT(       1)
       COMMON /NDAT6  /   NMDIF(       1)
       COMMON /NDAT7  /   NMARI(       1)
       COMMON /NDAT8  /   NMHT(       1)
       COMMON /NDAT9  /   NMBD(       1)
       COMMON /NDAT10 /   NDNAM(       1)
       COMMON /NDAT11 /   NDINT(       1)
       COMMON /NDAT12 /   TOLD(       1)
       CHARACTER*8        NMOD    ,NDNAM
        COMMON /TAPES  /   NIN    ,NOUT   ,NCOND  ,NNODE
     +                ,NOSORC ,NOARRY ,NOCARY ,NOTARY
     +                ,NVCD   ,NVGD   ,NOUSER ,NOCNTR
     +                ,NOUSE  ,NETQF  ,NXTRA1 ,NXTRA2
     +                ,NTSV   ,NUSER1 ,NUSER2 ,NRSI
     +                ,NRSO   ,NPARAM ,NFLOW  ,NFLOW2
     +                ,NFLOW3 ,NOOPT  ,NSCR1  ,NSCR2
     +                ,NSCR3  ,NSCR4  ,NQMP   ,NFPROP
       COMMON /CDAT1  /   PT(       1)
       COMMON /CDAT2  /   PG(       1)
       COMMON /CDAT3  /   NLIN(       1)
       COMMON /CDAT4  /   NRAD(       1)
       COMMON /CDAT5  /   NFLO(      13)
       COMMON /CDAT7  /   NCTOT(       1)
       COMMON /CDAT8  /   NGSTRT(       1)
       COMMON /CDAT9  /   G(       1)
       INTEGER            PT      , PG      , NLIN    , NRAD
       INTEGER            NCTOT   , NGSTRT
            COMMON /CCONST /   MMODS  ,NNOD   ,ABSZRO ,SIGMA  ,NMACT
     +                  ,DATE   ,TIMDY  ,LINECT ,PAGECT ,DTIMES
     +                  ,TIMEN  ,TIMEO  ,TIMEM  ,TIMEND ,NLOOPS
     +                  ,LOOPCT ,MLINE
        INTEGER LINECT,PAGECT
        COMMON /NUMCON /   K(       1)
       COMMON /ARAYS  /   A(       1)
       COMMON /CARAYS /   UCA(       1)
       DIMENSION          XK(1)   , NA(1)
       CHARACTER*128 UCA
       EQUIVALENCE (K(1), XK(1))
       EQUIVALENCE (A(1), NA(1))
      COMMON/USER/ ATEST,BTEST,CTEST,DTEST,ETEST,FTEST,GTEST,HTEST,ITEST
     +,JTEST,KTEST,LTEST,MTEST,NTEST,OTEST,PTEST,QTEST,RTEST,STEST,TTEST
     +,UTEST,VTEST,WTEST,XTEST,YTEST,ZTEST,TOTMAS,CVINIT
       EXTERNAL CTF,CTK,FTC,FTK,FTR,KTC,KTF,RTF
       EXTERNAL TPRINT,QPRINT,CPRINT,GPRINT
       COMMON /SOLTYP/ NSOL
        CALL CHOKER( 'FILLIT' , 20 , 1 , 0.0000000 )
       RETURN
       END
       SUBROUTINE FL2001
       PARAMETER(MXNODE= 20000, MXCOND= 100000, MXUARY=  5000)
       PARAMETER(MXTARY=  10000,MXMODS=100,  MXTOKN=80)
       PARAMETER(MXCNTR=76,MXUCON= 1000,  MXNCON= 5000)
       PARAMETER(MXFRES=196,MXFILE=17,  MXFLID= 30)
       PARAMETER(MXMODF=100)
        COMMON /FLUDAT/ FI(90),FDATA(1700)
        INTEGER FI
        DOUBLE PRECISION VPS,VPGMAX
       PARAMETER (MXFMOD=        1)
       PARAMETER (MXLUMP=        3)
       PARAMETER (MXTANK=        2)
       PARAMETER (MXJUNC=        1)
       PARAMETER (MXPLEN=        1)
       PARAMETER (MXPATH=        2)
       PARAMETER (MXTUBE=        1)
       PARAMETER (MXCONN=        2)
       PARAMETER (KCMAX=       36)
       PARAMETER (NDMAX=        6)
       PARAMETER (NOMAX=        6)
       PARAMETER (NIA=       14)
       PARAMETER (NJA=       72)
       PARAMETER (NARO=       12)
       PARAMETER (NWORKT=      440)
       PARAMETER (MXTIE =        1)
       PARAMETER (MXMACS=        1)
       PARAMETER (MXGNLU=        1)
       PARAMETER (MXGNCN=        1)
       PARAMETER (MXGNTI=        1)
        COMMON/LUMP4 / HL(MXLUMP)
        COMMON/LUMP5 / PL(MXLUMP)
        COMMON/LUMP6 / XL(MXLUMP)
        COMMON/LUMP7 / TL(MXLUMP)
        COMMON/LUMP7A/ DL(MXLUMP)
        COMMON/LUMP10/ VOL(MXTANK)
        COMMON/LUMP11/ VDOT(MXTANK)
        COMMON/LUMP12/ QDOT(MXLUMP)
        DOUBLE PRECISION PL
        COMMON/LUMP30/ COMP(MXTANK)
        COMMON/LUMP31/ CX(MXLUMP)
        COMMON/LUMP32/ CY(MXLUMP)
        COMMON/LUMP33/ CZ(MXLUMP)
        COMMON /TIEDAF/ QTIE(MXTIE)
        COMMON /TIEDAN/ DUPL(MXTIE)
        COMMON /TIEDAO/ DUPN(MXTIE)
        COMMON /TIEDA7/ UA(MXTIE)
        COMMON/PATH3 / FR(MXPATH)
        COMMON/PATH4 / HC(MXPATH)
        COMMON/PATH5 / FC(MXPATH)
        COMMON/PATH6 / AC(MXPATH)
        COMMON/PATH7 / GK(MXPATH)
        COMMON/PATH10/ HK(MXPATH)
        COMMON/PATH13/ DH(MXPATH)
        COMMON/PATH14/ TLEN(MXPATH)
        COMMON/PATH15/ AF(MXPATH)
        COMMON/PATH16/ WRF(MXPATH)
        COMMON/PATH17/ UPF(MXPATH)
        COMMON/PATH18/ IPDC(MXPATH)
        COMMON/PATH23/ DUPI(MXPATH)
        COMMON/PATH24/ DUPJ(MXPATH)
        COMMON/PATH26/ FPOW(MXPATH)
        COMMON/PATH30/ EI(MXPATH)
        COMMON/PATH31/ EJ(MXPATH)
        COMMON/PATH32/ DK(MXPATH)
        COMMON/PATH33/ FD(MXPATH)
        COMMON/PATH34/ FG(MXPATH)
        COMMON/PATH35/ AM(MXTUBE)
        COMMON/PATH40/ AFTH(MXPATH)
        COMMON/PATH41/ FK(MXPATH)
        COMMON/SOLN23/ NZZZZ1,NZZZZ2,NZZZZ3,DTIMUF(MXFMOD)
        COMMON/FSIZ1 / NFM,NTL,NTT,NTJ,NTPL,NTK,NTTB,NTC
        COMMON/FSIZ2 / NUMTNK(MXFMOD)
        COMMON/FSIZ3 / NUMJNC(MXFMOD)
        COMMON/FSIZ4 / NUMPLE(MXFMOD)
        COMMON/FSIZ5 / NUMTUB(MXFMOD)
        COMMON/FSIZ6 / NUMCNT(MXFMOD)
        COMMON/FSIZ7 / NTOTL(MXFMOD)
        COMMON/FSIZ8 / NTOTK(MXFMOD)
        COMMON/FSIZ11/ FLID(MXFMOD)
        INTEGER FLID
        COMMON/FLUCNT/DTSIZF(MXMODF),DTMAXF(MXMODF),OUTPTF(MXMODF),
     . RSSIZF(MXMODF) ,RSMAXF(MXMODF) ,RERRF(MXMODF),
     . REBALF(MXMODF) ,ITROTF(MXMODF) ,OPITRF(MXMODF),
     . DTMINF(MXMODF) ,ITHLDF(MXMODF),
     . DTTUBF(MXMODF) ,RSTUBF(MXMODF)
        COMMON /FLUCN1/ PATMOS,UID,ACCELX,ACCELY,ACCELZ
        DOUBLE PRECISION PATMOS
        INTEGER UID
       COMMON /CNTRL1 /
     +       DTIMEU(MXMODS) , DTIMEI(MXMODS) , DTIMEL(MXMODS)
     +     , DTIMEH(MXMODS) , OUTPUT(MXMODS) , DTMPCC(MXMODS)
     +     , DTMPCA(MXMODS) , NDTMPN(MXMODS) , ITHOLD(MXMODS)
     +     , ATMPCA(MXMODS) , NATMPN(MXMODS) , DRLXCA(MXMODS)
     +     , NDRLXN(MXMODS) , ARLXCA(MXMODS) , ARLXCC(MXMODS)
     +     , NARLXN(MXMODS) , CSGMIN(MXMODS) , CSGFAC(MXMODS)
     +     , CSGMAX(MXMODS) , NCSGMN(MXMODS) , NCGMAN(MXMODS)
     +     , EBALSA(MXMODS) , EBALNA(MXMODS) , EBALSC(MXMODS)
     +     , EBALNC(MXMODS) , NEBALN(MXMODS) , NLOOPT(MXMODS)
     +     , EXTLIM(MXMODS) , ITERXT(MXMODS) , ITEROT(MXMODS)
     +     , BACKUP(MXMODS) , OPEITR(MXMODS) , DRLXCC(MXMODS)
     +     , ATMPCC(MXMODS) , ESUMIS(MXMODS) , ESUMOS(MXMODS)
       INTEGER            OPEITR
C
       COMMON /CNTRL2 /   NDTMPC(MXMODS) , NATMPC(MXMODS)
     +     , NDRLXC(MXMODS) , NARLXC(MXMODS) , NCSGMC(MXMODS)
     +     , NCGMAC(MXMODS) , NEBALC(MXMODS)
       CHARACTER*8        NDTMPC      , NATMPC
     +                  , NDRLXC      , NARLXC      , NCSGMC
     +                  , NCGMAC      , NEBALC
C
       COMMON /NDAT1  /   T(       1)
       COMMON /NDAT2  /   C(       1)
       COMMON /NDAT3  /   Q(       1)
       COMMON /NDAT4  /   NMOD(       1)
       COMMON /NDAT5  /   NSTRT(       1)
       COMMON /NDAT6  /   NMDIF(       1)
       COMMON /NDAT7  /   NMARI(       1)
       COMMON /NDAT8  /   NMHT(       1)
       COMMON /NDAT9  /   NMBD(       1)
       COMMON /NDAT10 /   NDNAM(       1)
       COMMON /NDAT11 /   NDINT(       1)
       COMMON /NDAT12 /   TOLD(       1)
       CHARACTER*8        NMOD    ,NDNAM
        COMMON /TAPES  /   NIN    ,NOUT   ,NCOND  ,NNODE
     +                ,NOSORC ,NOARRY ,NOCARY ,NOTARY
     +                ,NVCD   ,NVGD   ,NOUSER ,NOCNTR
     +                ,NOUSE  ,NETQF  ,NXTRA1 ,NXTRA2
     +                ,NTSV   ,NUSER1 ,NUSER2 ,NRSI
     +                ,NRSO   ,NPARAM ,NFLOW  ,NFLOW2
     +                ,NFLOW3 ,NOOPT  ,NSCR1  ,NSCR2
     +                ,NSCR3  ,NSCR4  ,NQMP   ,NFPROP
       COMMON /CDAT1  /   PT(       1)
       COMMON /CDAT2  /   PG(       1)
       COMMON /CDAT3  /   NLIN(       1)
       COMMON /CDAT4  /   NRAD(       1)
       COMMON /CDAT5  /   NFLO(      13)
       COMMON /CDAT7  /   NCTOT(       1)
       COMMON /CDAT8  /   NGSTRT(       1)
       COMMON /CDAT9  /   G(       1)
       INTEGER            PT      , PG      , NLIN    , NRAD
       INTEGER            NCTOT   , NGSTRT
            COMMON /CCONST /   MMODS  ,NNOD   ,ABSZRO ,SIGMA  ,NMACT
     +                  ,DATE   ,TIMDY  ,LINECT ,PAGECT ,DTIMES
     +                  ,TIMEN  ,TIMEO  ,TIMEM  ,TIMEND ,NLOOPS
     +                  ,LOOPCT ,MLINE
        INTEGER LINECT,PAGECT
        COMMON /NUMCON /   K(       1)
       COMMON /ARAYS  /   A(       1)
       COMMON /CARAYS /   UCA(       1)
       DIMENSION          XK(1)   , NA(1)
       CHARACTER*128 UCA
       EQUIVALENCE (K(1), XK(1))
       EQUIVALENCE (A(1), NA(1))
      COMMON/USER/ ATEST,BTEST,CTEST,DTEST,ETEST,FTEST,GTEST,HTEST,ITEST
     +,JTEST,KTEST,LTEST,MTEST,NTEST,OTEST,PTEST,QTEST,RTEST,STEST,TTEST
     +,UTEST,VTEST,WTEST,XTEST,YTEST,ZTEST,TOTMAS,CVINIT
       EXTERNAL CTF,CTK,FTC,FTK,FTR,KTC,KTF,RTF
       EXTERNAL TPRINT,QPRINT,CPRINT,GPRINT
       COMMON /SOLTYP/ NSOL
        IF ( FR(     2) .LE. 0.0000000 ) THEN
        OUTPTF  (  1) = 9.99999978E-03
        ELSE
        OUTPTF  (  1) = 9.99999978E-03 * DL(     2) / FR(     2)
        ENDIF
        IF ( VOL(     2) .GE. 1.0000000 ) TIMEND = TIMEN
       RETURN
       END
       SUBROUTINE FL0001
       PARAMETER(MXNODE= 20000, MXCOND= 100000, MXUARY=  5000)
       PARAMETER(MXTARY=  10000,MXMODS=100,  MXTOKN=80)
       PARAMETER(MXCNTR=76,MXUCON= 1000,  MXNCON= 5000)
       PARAMETER(MXFRES=196,MXFILE=17,  MXFLID= 30)
       PARAMETER(MXMODF=100)
        COMMON /FLUDAT/ FI(90),FDATA(1700)
        INTEGER FI
        DOUBLE PRECISION VPS,VPGMAX
       PARAMETER (MXFMOD=        1)
       PARAMETER (MXLUMP=        3)
       PARAMETER (MXTANK=        2)
       PARAMETER (MXJUNC=        1)
       PARAMETER (MXPLEN=        1)
       PARAMETER (MXPATH=        2)
       PARAMETER (MXTUBE=        1)
       PARAMETER (MXCONN=        2)
       PARAMETER (KCMAX=       36)
       PARAMETER (NDMAX=        6)
       PARAMETER (NOMAX=        6)
       PARAMETER (NIA=       14)
       PARAMETER (NJA=       72)
       PARAMETER (NARO=       12)
       PARAMETER (NWORKT=      440)
       PARAMETER (MXTIE =        1)
       PARAMETER (MXMACS=        1)
       PARAMETER (MXGNLU=        1)
       PARAMETER (MXGNCN=        1)
       PARAMETER (MXGNTI=        1)
        COMMON/LUMP4 / HL(MXLUMP)
        COMMON/LUMP5 / PL(MXLUMP)
        COMMON/LUMP6 / XL(MXLUMP)
        COMMON/LUMP7 / TL(MXLUMP)
        COMMON/LUMP7A/ DL(MXLUMP)
        COMMON/LUMP10/ VOL(MXTANK)
        COMMON/LUMP11/ VDOT(MXTANK)
        COMMON/LUMP12/ QDOT(MXLUMP)
        DOUBLE PRECISION PL
        COMMON/LUMP30/ COMP(MXTANK)
        COMMON/LUMP31/ CX(MXLUMP)
        COMMON/LUMP32/ CY(MXLUMP)
        COMMON/LUMP33/ CZ(MXLUMP)
        COMMON /TIEDAF/ QTIE(MXTIE)
        COMMON /TIEDAN/ DUPL(MXTIE)
        COMMON /TIEDAO/ DUPN(MXTIE)
        COMMON /TIEDA7/ UA(MXTIE)
        COMMON/PATH3 / FR(MXPATH)
        COMMON/PATH4 / HC(MXPATH)
        COMMON/PATH5 / FC(MXPATH)
        COMMON/PATH6 / AC(MXPATH)
        COMMON/PATH7 / GK(MXPATH)
        COMMON/PATH10/ HK(MXPATH)
        COMMON/PATH13/ DH(MXPATH)
        COMMON/PATH14/ TLEN(MXPATH)
        COMMON/PATH15/ AF(MXPATH)
        COMMON/PATH16/ WRF(MXPATH)
        COMMON/PATH17/ UPF(MXPATH)
        COMMON/PATH18/ IPDC(MXPATH)
        COMMON/PATH23/ DUPI(MXPATH)
        COMMON/PATH24/ DUPJ(MXPATH)
        COMMON/PATH26/ FPOW(MXPATH)
        COMMON/PATH30/ EI(MXPATH)
        COMMON/PATH31/ EJ(MXPATH)
        COMMON/PATH32/ DK(MXPATH)
        COMMON/PATH33/ FD(MXPATH)
        COMMON/PATH34/ FG(MXPATH)
        COMMON/PATH35/ AM(MXTUBE)
        COMMON/PATH40/ AFTH(MXPATH)
        COMMON/PATH41/ FK(MXPATH)
        COMMON/SOLN23/ NZZZZ1,NZZZZ2,NZZZZ3,DTIMUF(MXFMOD)
        COMMON/FSIZ1 / NFM,NTL,NTT,NTJ,NTPL,NTK,NTTB,NTC
        COMMON/FSIZ2 / NUMTNK(MXFMOD)
        COMMON/FSIZ3 / NUMJNC(MXFMOD)
        COMMON/FSIZ4 / NUMPLE(MXFMOD)
        COMMON/FSIZ5 / NUMTUB(MXFMOD)
        COMMON/FSIZ6 / NUMCNT(MXFMOD)
        COMMON/FSIZ7 / NTOTL(MXFMOD)
        COMMON/FSIZ8 / NTOTK(MXFMOD)
        COMMON/FSIZ11/ FLID(MXFMOD)
        INTEGER FLID
        COMMON/FLUCNT/DTSIZF(MXMODF),DTMAXF(MXMODF),OUTPTF(MXMODF),
     . RSSIZF(MXMODF) ,RSMAXF(MXMODF) ,RERRF(MXMODF),
     . REBALF(MXMODF) ,ITROTF(MXMODF) ,OPITRF(MXMODF),
     . DTMINF(MXMODF) ,ITHLDF(MXMODF),
     . DTTUBF(MXMODF) ,RSTUBF(MXMODF)
        COMMON /FLUCN1/ PATMOS,UID,ACCELX,ACCELY,ACCELZ
        DOUBLE PRECISION PATMOS
        INTEGER UID
       COMMON /CNTRL1 /
     +       DTIMEU(MXMODS) , DTIMEI(MXMODS) , DTIMEL(MXMODS)
     +     , DTIMEH(MXMODS) , OUTPUT(MXMODS) , DTMPCC(MXMODS)
     +     , DTMPCA(MXMODS) , NDTMPN(MXMODS) , ITHOLD(MXMODS)
     +     , ATMPCA(MXMODS) , NATMPN(MXMODS) , DRLXCA(MXMODS)
     +     , NDRLXN(MXMODS) , ARLXCA(MXMODS) , ARLXCC(MXMODS)
     +     , NARLXN(MXMODS) , CSGMIN(MXMODS) , CSGFAC(MXMODS)
     +     , CSGMAX(MXMODS) , NCSGMN(MXMODS) , NCGMAN(MXMODS)
     +     , EBALSA(MXMODS) , EBALNA(MXMODS) , EBALSC(MXMODS)
     +     , EBALNC(MXMODS) , NEBALN(MXMODS) , NLOOPT(MXMODS)
     +     , EXTLIM(MXMODS) , ITERXT(MXMODS) , ITEROT(MXMODS)
     +     , BACKUP(MXMODS) , OPEITR(MXMODS) , DRLXCC(MXMODS)
     +     , ATMPCC(MXMODS) , ESUMIS(MXMODS) , ESUMOS(MXMODS)
       INTEGER            OPEITR
C
       COMMON /CNTRL2 /   NDTMPC(MXMODS) , NATMPC(MXMODS)
     +     , NDRLXC(MXMODS) , NARLXC(MXMODS) , NCSGMC(MXMODS)
     +     , NCGMAC(MXMODS) , NEBALC(MXMODS)
       CHARACTER*8        NDTMPC      , NATMPC
     +                  , NDRLXC      , NARLXC      , NCSGMC
     +                  , NCGMAC      , NEBALC
C
       COMMON /NDAT1  /   T(       1)
       COMMON /NDAT2  /   C(       1)
       COMMON /NDAT3  /   Q(       1)
       COMMON /NDAT4  /   NMOD(       1)
       COMMON /NDAT5  /   NSTRT(       1)
       COMMON /NDAT6  /   NMDIF(       1)
       COMMON /NDAT7  /   NMARI(       1)
       COMMON /NDAT8  /   NMHT(       1)
       COMMON /NDAT9  /   NMBD(       1)
       COMMON /NDAT10 /   NDNAM(       1)
       COMMON /NDAT11 /   NDINT(       1)
       COMMON /NDAT12 /   TOLD(       1)
       CHARACTER*8        NMOD    ,NDNAM
        COMMON /TAPES  /   NIN    ,NOUT   ,NCOND  ,NNODE
     +                ,NOSORC ,NOARRY ,NOCARY ,NOTARY
     +                ,NVCD   ,NVGD   ,NOUSER ,NOCNTR
     +                ,NOUSE  ,NETQF  ,NXTRA1 ,NXTRA2
     +                ,NTSV   ,NUSER1 ,NUSER2 ,NRSI
     +                ,NRSO   ,NPARAM ,NFLOW  ,NFLOW2
     +                ,NFLOW3 ,NOOPT  ,NSCR1  ,NSCR2
     +                ,NSCR3  ,NSCR4  ,NQMP   ,NFPROP
       COMMON /CDAT1  /   PT(       1)
       COMMON /CDAT2  /   PG(       1)
       COMMON /CDAT3  /   NLIN(       1)
       COMMON /CDAT4  /   NRAD(       1)
       COMMON /CDAT5  /   NFLO(      13)
       COMMON /CDAT7  /   NCTOT(       1)
       COMMON /CDAT8  /   NGSTRT(       1)
       COMMON /CDAT9  /   G(       1)
       INTEGER            PT      , PG      , NLIN    , NRAD
       INTEGER            NCTOT   , NGSTRT
            COMMON /CCONST /   MMODS  ,NNOD   ,ABSZRO ,SIGMA  ,NMACT
     +                  ,DATE   ,TIMDY  ,LINECT ,PAGECT ,DTIMES
     +                  ,TIMEN  ,TIMEO  ,TIMEM  ,TIMEND ,NLOOPS
     +                  ,LOOPCT ,MLINE
        INTEGER LINECT,PAGECT
        COMMON /NUMCON /   K(       1)
       COMMON /ARAYS  /   A(       1)
       COMMON /CARAYS /   UCA(       1)
       DIMENSION          XK(1)   , NA(1)
       CHARACTER*128 UCA
       EQUIVALENCE (K(1), XK(1))
       EQUIVALENCE (A(1), NA(1))
      COMMON/USER/ ATEST,BTEST,CTEST,DTEST,ETEST,FTEST,GTEST,HTEST,ITEST
     +,JTEST,KTEST,LTEST,MTEST,NTEST,OTEST,PTEST,QTEST,RTEST,STEST,TTEST
     +,UTEST,VTEST,WTEST,XTEST,YTEST,ZTEST,TOTMAS,CVINIT
       EXTERNAL CTF,CTK,FTC,FTK,FTR,KTC,KTF,RTF
       EXTERNAL TPRINT,QPRINT,CPRINT,GPRINT
       COMMON /SOLTYP/ NSOL
        COMP(     2) = CVINIT * VOL(     2)
       RETURN
       END
       SUBROUTINE OPER
       PARAMETER(MXNODE= 20000, MXCOND= 100000, MXUARY=  5000)
       PARAMETER(MXTARY=  10000,MXMODS=100,  MXTOKN=80)
       PARAMETER(MXCNTR=76,MXUCON= 1000,  MXNCON= 5000)
       PARAMETER(MXFRES=196,MXFILE=17,  MXFLID= 30)
       PARAMETER(MXMODF=100)
        COMMON /FLUDAT/ FI(90),FDATA(1700)
        INTEGER FI
        DOUBLE PRECISION VPS,VPGMAX
       PARAMETER (MXFMOD=        1)
       PARAMETER (MXLUMP=        3)
       PARAMETER (MXTANK=        2)
       PARAMETER (MXJUNC=        1)
       PARAMETER (MXPLEN=        1)
       PARAMETER (MXPATH=        2)
       PARAMETER (MXTUBE=        1)
       PARAMETER (MXCONN=        2)
       PARAMETER (KCMAX=       36)
       PARAMETER (NDMAX=        6)
       PARAMETER (NOMAX=        6)
       PARAMETER (NIA=       14)
       PARAMETER (NJA=       72)
       PARAMETER (NARO=       12)
       PARAMETER (NWORKT=      440)
       PARAMETER (MXTIE =        1)
       PARAMETER (MXMACS=        1)
       PARAMETER (MXGNLU=        1)
       PARAMETER (MXGNCN=        1)
       PARAMETER (MXGNTI=        1)
        COMMON/LUMP4 / HL(MXLUMP)
        COMMON/LUMP5 / PL(MXLUMP)
        COMMON/LUMP6 / XL(MXLUMP)
        COMMON/LUMP7 / TL(MXLUMP)
        COMMON/LUMP7A/ DL(MXLUMP)
        COMMON/LUMP10/ VOL(MXTANK)
        COMMON/LUMP11/ VDOT(MXTANK)
        COMMON/LUMP12/ QDOT(MXLUMP)
        DOUBLE PRECISION PL
        COMMON/LUMP30/ COMP(MXTANK)
        COMMON/LUMP31/ CX(MXLUMP)
        COMMON/LUMP32/ CY(MXLUMP)
        COMMON/LUMP33/ CZ(MXLUMP)
        COMMON /TIEDAF/ QTIE(MXTIE)
        COMMON /TIEDAN/ DUPL(MXTIE)
        COMMON /TIEDAO/ DUPN(MXTIE)
        COMMON /TIEDA7/ UA(MXTIE)
        COMMON/PATH3 / FR(MXPATH)
        COMMON/PATH4 / HC(MXPATH)
        COMMON/PATH5 / FC(MXPATH)
        COMMON/PATH6 / AC(MXPATH)
        COMMON/PATH7 / GK(MXPATH)
        COMMON/PATH10/ HK(MXPATH)
        COMMON/PATH13/ DH(MXPATH)
        COMMON/PATH14/ TLEN(MXPATH)
        COMMON/PATH15/ AF(MXPATH)
        COMMON/PATH16/ WRF(MXPATH)
        COMMON/PATH17/ UPF(MXPATH)
        COMMON/PATH18/ IPDC(MXPATH)
        COMMON/PATH23/ DUPI(MXPATH)
        COMMON/PATH24/ DUPJ(MXPATH)
        COMMON/PATH26/ FPOW(MXPATH)
        COMMON/PATH30/ EI(MXPATH)
        COMMON/PATH31/ EJ(MXPATH)
        COMMON/PATH32/ DK(MXPATH)
        COMMON/PATH33/ FD(MXPATH)
        COMMON/PATH34/ FG(MXPATH)
        COMMON/PATH35/ AM(MXTUBE)
        COMMON/PATH40/ AFTH(MXPATH)
        COMMON/PATH41/ FK(MXPATH)
        COMMON/SOLN23/ NZZZZ1,NZZZZ2,NZZZZ3,DTIMUF(MXFMOD)
        COMMON/FSIZ1 / NFM,NTL,NTT,NTJ,NTPL,NTK,NTTB,NTC
        COMMON/FSIZ2 / NUMTNK(MXFMOD)
        COMMON/FSIZ3 / NUMJNC(MXFMOD)
        COMMON/FSIZ4 / NUMPLE(MXFMOD)
        COMMON/FSIZ5 / NUMTUB(MXFMOD)
        COMMON/FSIZ6 / NUMCNT(MXFMOD)
        COMMON/FSIZ7 / NTOTL(MXFMOD)
        COMMON/FSIZ8 / NTOTK(MXFMOD)
        COMMON/FSIZ11/ FLID(MXFMOD)
        INTEGER FLID
        COMMON/FLUCNT/DTSIZF(MXMODF),DTMAXF(MXMODF),OUTPTF(MXMODF),
     . RSSIZF(MXMODF) ,RSMAXF(MXMODF) ,RERRF(MXMODF),
     . REBALF(MXMODF) ,ITROTF(MXMODF) ,OPITRF(MXMODF),
     . DTMINF(MXMODF) ,ITHLDF(MXMODF),
     . DTTUBF(MXMODF) ,RSTUBF(MXMODF)
        COMMON /FLUCN1/ PATMOS,UID,ACCELX,ACCELY,ACCELZ
        DOUBLE PRECISION PATMOS
        INTEGER UID
       COMMON /CNTRL1 /
     +       DTIMEU(MXMODS) , DTIMEI(MXMODS) , DTIMEL(MXMODS)
     +     , DTIMEH(MXMODS) , OUTPUT(MXMODS) , DTMPCC(MXMODS)
     +     , DTMPCA(MXMODS) , NDTMPN(MXMODS) , ITHOLD(MXMODS)
     +     , ATMPCA(MXMODS) , NATMPN(MXMODS) , DRLXCA(MXMODS)
     +     , NDRLXN(MXMODS) , ARLXCA(MXMODS) , ARLXCC(MXMODS)
     +     , NARLXN(MXMODS) , CSGMIN(MXMODS) , CSGFAC(MXMODS)
     +     , CSGMAX(MXMODS) , NCSGMN(MXMODS) , NCGMAN(MXMODS)
     +     , EBALSA(MXMODS) , EBALNA(MXMODS) , EBALSC(MXMODS)
     +     , EBALNC(MXMODS) , NEBALN(MXMODS) , NLOOPT(MXMODS)
     +     , EXTLIM(MXMODS) , ITERXT(MXMODS) , ITEROT(MXMODS)
     +     , BACKUP(MXMODS) , OPEITR(MXMODS) , DRLXCC(MXMODS)
     +     , ATMPCC(MXMODS) , ESUMIS(MXMODS) , ESUMOS(MXMODS)
       INTEGER            OPEITR
C
       COMMON /CNTRL2 /   NDTMPC(MXMODS) , NATMPC(MXMODS)
     +     , NDRLXC(MXMODS) , NARLXC(MXMODS) , NCSGMC(MXMODS)
     +     , NCGMAC(MXMODS) , NEBALC(MXMODS)
       CHARACTER*8        NDTMPC      , NATMPC
     +                  , NDRLXC      , NARLXC      , NCSGMC
     +                  , NCGMAC      , NEBALC
C
       COMMON /NDAT1  /   T(       1)
       COMMON /NDAT2  /   C(       1)
       COMMON /NDAT3  /   Q(       1)
       COMMON /NDAT4  /   NMOD(       1)
       COMMON /NDAT5  /   NSTRT(       1)
       COMMON /NDAT6  /   NMDIF(       1)
       COMMON /NDAT7  /   NMARI(       1)
       COMMON /NDAT8  /   NMHT(       1)
       COMMON /NDAT9  /   NMBD(       1)
       COMMON /NDAT10 /   NDNAM(       1)
       COMMON /NDAT11 /   NDINT(       1)
       COMMON /NDAT12 /   TOLD(       1)
       CHARACTER*8        NMOD    ,NDNAM
        COMMON /TAPES  /   NIN    ,NOUT   ,NCOND  ,NNODE
     +                ,NOSORC ,NOARRY ,NOCARY ,NOTARY
     +                ,NVCD   ,NVGD   ,NOUSER ,NOCNTR
     +                ,NOUSE  ,NETQF  ,NXTRA1 ,NXTRA2
     +                ,NTSV   ,NUSER1 ,NUSER2 ,NRSI
     +                ,NRSO   ,NPARAM ,NFLOW  ,NFLOW2
     +                ,NFLOW3 ,NOOPT  ,NSCR1  ,NSCR2
     +                ,NSCR3  ,NSCR4  ,NQMP   ,NFPROP
       COMMON /CDAT1  /   PT(       1)
       COMMON /CDAT2  /   PG(       1)
       COMMON /CDAT3  /   NLIN(       1)
       COMMON /CDAT4  /   NRAD(       1)
       COMMON /CDAT5  /   NFLO(      13)
       COMMON /CDAT7  /   NCTOT(       1)
       COMMON /CDAT8  /   NGSTRT(       1)
       COMMON /CDAT9  /   G(       1)
       INTEGER            PT      , PG      , NLIN    , NRAD
       INTEGER            NCTOT   , NGSTRT
            COMMON /CCONST /   MMODS  ,NNOD   ,ABSZRO ,SIGMA  ,NMACT
     +                  ,DATE   ,TIMDY  ,LINECT ,PAGECT ,DTIMES
     +                  ,TIMEN  ,TIMEO  ,TIMEM  ,TIMEND ,NLOOPS
     +                  ,LOOPCT ,MLINE
        INTEGER LINECT,PAGECT
        COMMON /NUMCON /   K(       1)
       COMMON /ARAYS  /   A(       1)
       COMMON /CARAYS /   UCA(       1)
       DIMENSION          XK(1)   , NA(1)
       CHARACTER*128 UCA
       EQUIVALENCE (K(1), XK(1))
       EQUIVALENCE (A(1), NA(1))
      COMMON/USER/ ATEST,BTEST,CTEST,DTEST,ETEST,FTEST,GTEST,HTEST,ITEST
     +,JTEST,KTEST,LTEST,MTEST,NTEST,OTEST,PTEST,QTEST,RTEST,STEST,TTEST
     +,UTEST,VTEST,WTEST,XTEST,YTEST,ZTEST,TOTMAS,CVINIT
       EXTERNAL CTF,CTK,FTC,FTK,FTR,KTC,KTF,RTF
       EXTERNAL TPRINT,QPRINT,CPRINT,GPRINT
       COMMON /SOLTYP/ NSOL
       CHARACTER*8 NBNAM( 100)
       CHARACTER*8 NFNAM( 100)
       NFNAM(  1) = 'FILLIT  '
       CALL BUILDF('CONFIG  ',  1, NFNAM)
        TIMEND = 10.000000
        TOTMAS = VOL(     1) * DL(     1) + DUPI(     2) * VOL(     2) *
     . DL(     2)
        WRITE ( NUSER1 , 10 ) TOTMAS
        CALL FORWRD
        TOTMAS = VOL(     1) * DL(     1) + DUPI(     2) * VOL(     2) *
     . DL(     2)
        WRITE ( NUSER1 , 20 ) TOTMAS , TL(     1) , TL(     2)
 100    CONTINUE
10	FORMAT(' THE INITIAL SYSTEM MASS IS:',T40,1PG13.5///
     .	'   TIME (SEC)',T25,'P SUPPLY',T45,'FLOWRATE',
     .	T65,'P BALLOON',T85,'V BALLOON',T105,'COMPLIANCE'/)
20	FORMAT(//' THE FINAL SYSTEM MASS IS:',T40,1PG13.5/
     .	' THE FINAL SUPPLY TEMPERATURE IS:',T40,G13.5/
     .	' THE FINAL BALLOON TEMPERATURE IS:',T40,G13.5)
       RETURN
       END
       SUBROUTINE OUF001
       PARAMETER(MXNODE= 20000, MXCOND= 100000, MXUARY=  5000)
       PARAMETER(MXTARY=  10000,MXMODS=100,  MXTOKN=80)
       PARAMETER(MXCNTR=76,MXUCON= 1000,  MXNCON= 5000)
       PARAMETER(MXFRES=196,MXFILE=17,  MXFLID= 30)
       PARAMETER(MXMODF=100)
        COMMON /FLUDAT/ FI(90),FDATA(1700)
        INTEGER FI
        DOUBLE PRECISION VPS,VPGMAX
       PARAMETER (MXFMOD=        1)
       PARAMETER (MXLUMP=        3)
       PARAMETER (MXTANK=        2)
       PARAMETER (MXJUNC=        1)
       PARAMETER (MXPLEN=        1)
       PARAMETER (MXPATH=        2)
       PARAMETER (MXTUBE=        1)
       PARAMETER (MXCONN=        2)
       PARAMETER (KCMAX=       36)
       PARAMETER (NDMAX=        6)
       PARAMETER (NOMAX=        6)
       PARAMETER (NIA=       14)
       PARAMETER (NJA=       72)
       PARAMETER (NARO=       12)
       PARAMETER (NWORKT=      440)
       PARAMETER (MXTIE =        1)
       PARAMETER (MXMACS=        1)
       PARAMETER (MXGNLU=        1)
       PARAMETER (MXGNCN=        1)
       PARAMETER (MXGNTI=        1)
        COMMON/LUMP4 / HL(MXLUMP)
        COMMON/LUMP5 / PL(MXLUMP)
        COMMON/LUMP6 / XL(MXLUMP)
        COMMON/LUMP7 / TL(MXLUMP)
        COMMON/LUMP7A/ DL(MXLUMP)
        COMMON/LUMP10/ VOL(MXTANK)
        COMMON/LUMP11/ VDOT(MXTANK)
        COMMON/LUMP12/ QDOT(MXLUMP)
        DOUBLE PRECISION PL
        COMMON/LUMP30/ COMP(MXTANK)
        COMMON/LUMP31/ CX(MXLUMP)
        COMMON/LUMP32/ CY(MXLUMP)
        COMMON/LUMP33/ CZ(MXLUMP)
        COMMON /TIEDAF/ QTIE(MXTIE)
        COMMON /TIEDAN/ DUPL(MXTIE)
        COMMON /TIEDAO/ DUPN(MXTIE)
        COMMON /TIEDA7/ UA(MXTIE)
        COMMON/PATH3 / FR(MXPATH)
        COMMON/PATH4 / HC(MXPATH)
        COMMON/PATH5 / FC(MXPATH)
        COMMON/PATH6 / AC(MXPATH)
        COMMON/PATH7 / GK(MXPATH)
        COMMON/PATH10/ HK(MXPATH)
        COMMON/PATH13/ DH(MXPATH)
        COMMON/PATH14/ TLEN(MXPATH)
        COMMON/PATH15/ AF(MXPATH)
        COMMON/PATH16/ WRF(MXPATH)
        COMMON/PATH17/ UPF(MXPATH)
        COMMON/PATH18/ IPDC(MXPATH)
        COMMON/PATH23/ DUPI(MXPATH)
        COMMON/PATH24/ DUPJ(MXPATH)
        COMMON/PATH26/ FPOW(MXPATH)
        COMMON/PATH30/ EI(MXPATH)
        COMMON/PATH31/ EJ(MXPATH)
        COMMON/PATH32/ DK(MXPATH)
        COMMON/PATH33/ FD(MXPATH)
        COMMON/PATH34/ FG(MXPATH)
        COMMON/PATH35/ AM(MXTUBE)
        COMMON/PATH40/ AFTH(MXPATH)
        COMMON/PATH41/ FK(MXPATH)
        COMMON/SOLN23/ NZZZZ1,NZZZZ2,NZZZZ3,DTIMUF(MXFMOD)
        COMMON/FSIZ1 / NFM,NTL,NTT,NTJ,NTPL,NTK,NTTB,NTC
        COMMON/FSIZ2 / NUMTNK(MXFMOD)
        COMMON/FSIZ3 / NUMJNC(MXFMOD)
        COMMON/FSIZ4 / NUMPLE(MXFMOD)
        COMMON/FSIZ5 / NUMTUB(MXFMOD)
        COMMON/FSIZ6 / NUMCNT(MXFMOD)
        COMMON/FSIZ7 / NTOTL(MXFMOD)
        COMMON/FSIZ8 / NTOTK(MXFMOD)
        COMMON/FSIZ11/ FLID(MXFMOD)
        INTEGER FLID
        COMMON/FLUCNT/DTSIZF(MXMODF),DTMAXF(MXMODF),OUTPTF(MXMODF),
     . RSSIZF(MXMODF) ,RSMAXF(MXMODF) ,RERRF(MXMODF),
     . REBALF(MXMODF) ,ITROTF(MXMODF) ,OPITRF(MXMODF),
     . DTMINF(MXMODF) ,ITHLDF(MXMODF),
     . DTTUBF(MXMODF) ,RSTUBF(MXMODF)
        COMMON /FLUCN1/ PATMOS,UID,ACCELX,ACCELY,ACCELZ
        DOUBLE PRECISION PATMOS
        INTEGER UID
       COMMON /CNTRL1 /
     +       DTIMEU(MXMODS) , DTIMEI(MXMODS) , DTIMEL(MXMODS)
     +     , DTIMEH(MXMODS) , OUTPUT(MXMODS) , DTMPCC(MXMODS)
     +     , DTMPCA(MXMODS) , NDTMPN(MXMODS) , ITHOLD(MXMODS)
     +     , ATMPCA(MXMODS) , NATMPN(MXMODS) , DRLXCA(MXMODS)
     +     , NDRLXN(MXMODS) , ARLXCA(MXMODS) , ARLXCC(MXMODS)
     +     , NARLXN(MXMODS) , CSGMIN(MXMODS) , CSGFAC(MXMODS)
     +     , CSGMAX(MXMODS) , NCSGMN(MXMODS) , NCGMAN(MXMODS)
     +     , EBALSA(MXMODS) , EBALNA(MXMODS) , EBALSC(MXMODS)
     +     , EBALNC(MXMODS) , NEBALN(MXMODS) , NLOOPT(MXMODS)
     +     , EXTLIM(MXMODS) , ITERXT(MXMODS) , ITEROT(MXMODS)
     +     , BACKUP(MXMODS) , OPEITR(MXMODS) , DRLXCC(MXMODS)
     +     , ATMPCC(MXMODS) , ESUMIS(MXMODS) , ESUMOS(MXMODS)
       INTEGER            OPEITR
C
       COMMON /CNTRL2 /   NDTMPC(MXMODS) , NATMPC(MXMODS)
     +     , NDRLXC(MXMODS) , NARLXC(MXMODS) , NCSGMC(MXMODS)
     +     , NCGMAC(MXMODS) , NEBALC(MXMODS)
       CHARACTER*8        NDTMPC      , NATMPC
     +                  , NDRLXC      , NARLXC      , NCSGMC
     +                  , NCGMAC      , NEBALC
C
       COMMON /NDAT1  /   T(       1)
       COMMON /NDAT2  /   C(       1)
       COMMON /NDAT3  /   Q(       1)
       COMMON /NDAT4  /   NMOD(       1)
       COMMON /NDAT5  /   NSTRT(       1)
       COMMON /NDAT6  /   NMDIF(       1)
       COMMON /NDAT7  /   NMARI(       1)
       COMMON /NDAT8  /   NMHT(       1)
       COMMON /NDAT9  /   NMBD(       1)
       COMMON /NDAT10 /   NDNAM(       1)
       COMMON /NDAT11 /   NDINT(       1)
       COMMON /NDAT12 /   TOLD(       1)
       CHARACTER*8        NMOD    ,NDNAM
        COMMON /TAPES  /   NIN    ,NOUT   ,NCOND  ,NNODE
     +                ,NOSORC ,NOARRY ,NOCARY ,NOTARY
     +                ,NVCD   ,NVGD   ,NOUSER ,NOCNTR
     +                ,NOUSE  ,NETQF  ,NXTRA1 ,NXTRA2
     +                ,NTSV   ,NUSER1 ,NUSER2 ,NRSI
     +                ,NRSO   ,NPARAM ,NFLOW  ,NFLOW2
     +                ,NFLOW3 ,NOOPT  ,NSCR1  ,NSCR2
     +                ,NSCR3  ,NSCR4  ,NQMP   ,NFPROP
       COMMON /CDAT1  /   PT(       1)
       COMMON /CDAT2  /   PG(       1)
       COMMON /CDAT3  /   NLIN(       1)
       COMMON /CDAT4  /   NRAD(       1)
       COMMON /CDAT5  /   NFLO(      13)
       COMMON /CDAT7  /   NCTOT(       1)
       COMMON /CDAT8  /   NGSTRT(       1)
       COMMON /CDAT9  /   G(       1)
       INTEGER            PT      , PG      , NLIN    , NRAD
       INTEGER            NCTOT   , NGSTRT
            COMMON /CCONST /   MMODS  ,NNOD   ,ABSZRO ,SIGMA  ,NMACT
     +                  ,DATE   ,TIMDY  ,LINECT ,PAGECT ,DTIMES
     +                  ,TIMEN  ,TIMEO  ,TIMEM  ,TIMEND ,NLOOPS
     +                  ,LOOPCT ,MLINE
        INTEGER LINECT,PAGECT
        COMMON /NUMCON /   K(       1)
       COMMON /ARAYS  /   A(       1)
       COMMON /CARAYS /   UCA(       1)
       DIMENSION          XK(1)   , NA(1)
       CHARACTER*128 UCA
       EQUIVALENCE (K(1), XK(1))
       EQUIVALENCE (A(1), NA(1))
      COMMON/USER/ ATEST,BTEST,CTEST,DTEST,ETEST,FTEST,GTEST,HTEST,ITEST
     +,JTEST,KTEST,LTEST,MTEST,NTEST,OTEST,PTEST,QTEST,RTEST,STEST,TTEST
     +,UTEST,VTEST,WTEST,XTEST,YTEST,ZTEST,TOTMAS,CVINIT
       EXTERNAL CTF,CTK,FTC,FTK,FTR,KTC,KTF,RTF
       EXTERNAL TPRINT,QPRINT,CPRINT,GPRINT
       COMMON /SOLTYP/ NSOL
        CALL LMPTAB( 'FILLIT' )
        CALL LMXTAB( 'FILLIT' )
        CALL PTHTAB( 'FILLIT' )
        WRITE ( NUSER1 , 10 ) 3600.0000 * TIMEN , PL(     1) ,
     . FR(     2)
     + , PL(     2) , VOL(     2) , COMP(     2)
 10	FORMAT(1X,6(1PG13.5,7X))
       RETURN
       END
       SUBROUTINE FLOGI0(MODNO)
       IF(MODNO .EQ. 1)   THEN
                CALL FL0001
       END IF
       RETURN
       END
       SUBROUTINE FLOGI1(MODNO)
       IF(MODNO .EQ. 1)   THEN
                CALL FL1001
       END IF
       RETURN
       END
       SUBROUTINE FLOGI2(MODNO)
       IF(MODNO .EQ. 1)   THEN
                CALL FL2001
       END IF
       RETURN
       END
       SUBROUTINE VARBL0(MODNO)
       RETURN
       END
       SUBROUTINE VARBL1(MODNO)
       RETURN
       END
       SUBROUTINE VARBL2(MODNO)
       RETURN
       END
       SUBROUTINE OUTCAL(MODNO)
       IF(MODNO .EQ. -1)   THEN
                CALL OUF001
       END IF
       RETURN
       END
